config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:show, :update]
  # get 'questions/:id', to: 'questions#show', as: 'question'
  get 'home' => 'home#index'
  get 'results', to: 'results#show'

  get 'questions/:id/past', to: 'questions#past', as: 'past_question'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "questions#show", id: 1
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
# app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :update]

  def show
    # 現在の質問を表示
  end

  def update
    if @question.update(question_params)
      # 次の質問のIDを計算
      next_question_id = @question.id + 1
      if Question.exists?(next_question_id)
        redirect_to question_path(next_question_id)
      else
        # 質問がない場合は、結果ページなどにリダイレクト
        redirect_to results_path
      end
    else
      # エラー処理
      render :show
    end
  end

  def past
    @question = Question.find(params[:id])

    pre_question_id = @question.id - 1
    if Question.exists?(pre_question_id)
      redirect_to question_path(pre_question_id)
    else
      redirect_to results_path
    end
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:answer)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  require 'json'
  def show
    mbti_alphabets = Question.all.map do |question|
      question[:answer] == 'A' ? question[:A_alphabet] : question[:B_alphabet]
    end
    @mbti_string = mbti_alphabets.join

    puts "mbti_string: #{@mbti_string}"

    file_path = Rails.root.join('public', 'json','mbti_data.json')
    file = File.read(file_path)
    mbti_data = JSON.parse(file)

    @mbti_features = mbti_data[@mbti_string]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/home/index.html.erb
<div class="first-block">
    <%# <button class="start_button" type="button"><a href="https://google.com">診断スタート</a></button> %>
    <%= button_to '診断スタート', question_path(1), method: :get, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benesse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <div class="flex-container">
      <header>
        <h1 class="headline">MBTI キャリアガイド</a></h1>
      </header>

      <%= yield %>

      <footer class="flex-footer">
        <p><small>&copy; 2023 benesse hackathon team7</p>
      </footer>
    </div>
  </body>
</html>

app/views/questions/show.html.erb
<!-- app/views/questions/show.html.erb -->
<main>
    <p><%= @question.question %></>
    <div class="button-to-form">
        <%= button_to "#{@question.choiceA}", question_path(@question, question: { answer: "A" }), method: :put,
        form_class: "a-button a-button--red a-button--radius a-button--cubic", class: "btn"%>


        <%= button_to "#{@question.choiceB}", question_path(@question, question: { answer: "B" }), method: :put,
        form_class: "b-button b-button--red b-button--radius b-button--cubic", class: "btn"%>

        <%= button_to "戻る", past_question_path(@question), method: :get, form_class: "b-button b-button--red b-button--radius b-button--cubic", class: "btn"%>
    <div>
</main>

app/views/results/show.html.erb
<!-- app/views/results/show.html.erb -->
<main>
  <p>あなたのMBTIは <%= @mbti_string %> です。</p>

  <h2>あなたの強み</h2>
  <ol>
    <% @mbti_features['strengths'].each do |feature| %>
      <li><%= feature %></li>
    <% end %>
  </ol>

  <h2>あなたの弱み</h2>
  <ol>
    <% @mbti_features['weaknesses'].each do |feature| %>
      <li><%= feature %></li>
    <% end %>
  </ol>

  <h2>あなたにぴったりの職業はこちら↓</h2>
  <div class="button-to-form">
    <%= button_to "プログラマー", '/result-job-programmer.html', method: :get, class: 'btn', form_class: "a-button a-button--red a-button--radius ba-button--cubic"%>
    <%= button_to "営業職", '/result-job-sales.html', method: :get, class: 'btn', form_class: "a-button a-button--red a-button--radius a-button--cubic"%>
  </div>

  <%= button_to "もう一度診断する", root_path, method: :get%>
</main>